Use cd instead of pushd/popd

diff --git a/client/send_request b/client/send_request
--- a/client/send_request
+++ b/client/send_request
@@ -29,10 +29,11 @@ function ProcessRequest {
 (
 flock -xn 300
 
-for N in ${RequestDir}/*
+cd "$RequestDir"
+for N in *
 do
 	if test -d "$N"; then
-		pushd "$N" || continue
+		cd "$N" || continue
 		
 		TODOdir=$(mktemp -d)
 		
@@ -73,7 +74,7 @@ EOF
 				set -e	
 				export GIT_DIR="${SendQueue}/$(basename ${N}).git"
 				test -d "$GIT_DIR"
-				pushd "$TODOdir"
+				cd "$TODOdir"
 		
 				git rm -rf --cached . 1>/dev/null 2>&1
 				git add RQ*
@@ -84,7 +85,6 @@ EOF
 				
 				git commit -m "${Launch_time}: see log '${Host}':'${Logfile}'"
 				git push origin +master:master
-				popd
 			) 1>>"$t2" 2>&1 || (cat "$t2" >> "$failog"; echo >> "$failog")
 	
 			cat "$t2" >> "$Logfile"; echo >> "$Logfile"
@@ -93,7 +93,7 @@ EOF
 		)
 
 		if test -s "$failog"; then
-			echo "Some error happens in backup ${Host} => ${N}, notifies $Administrators..."
+			echo "Some error happens in backup ${Host} => $RequestDir/$N, notifies $Administrators..."
 			"$Sendmail" -i $Administrators <<EOF
 Subject: [${Host}][${Launch_time}]errors in backup
 
@@ -114,7 +114,7 @@ EOF
 			rm -f "$F"
 		done
 
-		popd
+		cd ${RequestDir}
 	fi
 done
 
diff --git a/server/do_backup b/server/do_backup
--- a/server/do_backup
+++ b/server/do_backup
@@ -60,10 +60,11 @@ function ProcessRquest {
 (
 flock -xn 300
 
-for N in "$TODOdir"/*
+cd "$TODOdir"
+for N in *
 do
 	if test -d "$N"; then
-		pushd "$N" || continue
+		cd "$N" || continue
 
 		resumelog=$(mktemp)
 		for P in P*
@@ -92,7 +93,7 @@ EOF
 		done
 		
 		if test -s "$failog"; then
-			echo "Some error happens in backup ${Host} => ${N}, notifies $Administrators..."
+			echo "Some error happens in backup ${Host} => $TODOdir/$N, notifies $Administrators..."
 			"$Sendmail" -i $Administrators <<EOF
 Subject: [${Host}][${Launch_time}] errors in backup
 
@@ -107,7 +108,7 @@ EOF
 			rm -f "$F"
 		done
 
-		popd
+		cd "$TODOdir"
 	fi
 done
 
